#ifndef QSCREENSCRAPERAPICLIENT_GLOBAL_HPP
#define QSCREENSCRAPERAPICLIENT_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QSCREENSCRAPERAPICLIENT_LIBRARY)
#  define QSCREENSCRAPERAPICLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSCREENSCRAPERAPICLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSCREENSCRAPERAPICLIENT_GLOBAL_HPP
